name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0 * * *" # ainda corre todos os dias, mas sÃ³ executa a cada 2
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check if today should run
      id: check
      run: |
        if [ $(( ($(date +%s) / 86400) % 2 )) -ne 0 ]; then
          echo "run=false" >> $GITHUB_OUTPUT
          echo "Skipping - Not a scheduled day"
        else
          echo "run=true" >> $GITHUB_OUTPUT
          echo "Running - Today is a scheduled execution day"
        fi
      shell: bash

    - name: Checkout repository
      if: steps.check.outputs.run == 'true'
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      if: steps.check.outputs.run == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements
      if: steps.check.outputs.run == 'true'
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    - name: Generate images
      if: steps.check.outputs.run == 'true'
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    - name: Commit to the repo
      if: steps.check.outputs.run == 'true'
      run: |
        git config --global user.name "shadowoff09/github-stats"
        git config --global user.email "shadowdev.sys@gmail.com"
        git add .
        git commit -m 'Update stats' || true
        git push
